language: android
jdk: openjdk17

android:
  components:
    - tools
    - platform-tools
    - build-tools-35.0.0
    - android-35

before_install:
  - yes | sdkmanager "platforms;android-35"

script:
- ./gradlew check
